basePath: /products/procure-hub
definitions:
  api.LoginHandler.LoginData:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.User:
    description: User model to create a new user
    properties:
      companyName:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      primaryOwnerID:
        type: integer
      userType:
        $ref: '#/definitions/models.userType'
    required:
    - companyName
    - email
    - name
    - password
    - primaryOwnerID
    - userType
    type: object
  models.userType:
    enum:
    - primary_owner
    - client
    type: string
    x-enum-varnames:
    - PrimaryOwner
    - Client
info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /users/v1/login:
    post:
      consumes:
      - application/json
      description: Log in with the provided email and password.
      parameters:
      - description: User login request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api.LoginHandler.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            type: object
      summary: User Login
      tags:
      - Users
  /users/v1/signup:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided information.
      parameters:
      - description: User registration request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: object
        "409":
          description: Conflict
          schema:
            type: object
      summary: Register a new user
      tags:
      - Users
swagger: "2.0"
